spring:
  application:
    name: qa-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:0eab4d97-bb36-401e-8481-3b50d0963efe}
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:0eab4d97-bb36-401e-8481-3b50d0963efe}
        file-extension: yaml
        group: DEFAULT_GROUP
  config:
    import:
      - nacos:qa-gateway.yaml?group=DEFAULT_GROUP
