spring.application.name=report-admin

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.tomcat.uri-encoding=UTF-8

spring.config.import=optional:nacos:report-admin?group=DEFAULT_GROUP&refreshEnabled=true
spring.cloud.nacos.server-addr=${NACOS_SERVER_ADDR:127.0.0.1:8848}
spring.cloud.nacos.config.enabled=true
spring.cloud.nacos.config.group=DEFAULT_GROUP
spring.cloud.nacos.config.file-extension=properties

spring.cloud.nacos.discovery.enabled=true
spring.cloud.nacos.discovery.group=DEFAULT_GROUP
