CREATE TABLE IF NOT EXISTS sys_menu (
    id           BIGINT        NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    parent_id    BIGINT        NOT NULL DEFAULT 0 COMMENT '父菜单ID，0=顶级',
    ancestors    VARCHAR(500)  NOT NULL DEFAULT '0' COMMENT '祖先路径，如 0,12,34',
    level        TINYINT       NOT NULL DEFAULT 1 COMMENT '层级 1/2/3',
    menu_name    VARCHAR(100)  NOT NULL COMMENT '菜单名称',
    menu_code    VARCHAR(100)  NOT NULL COMMENT '菜单编码',
    route_path   VARCHAR(255)           DEFAULT NULL COMMENT 'Vue Router path',
    route_name   VARCHAR(100)           DEFAULT NULL COMMENT 'Vue Router name',
    component    VARCHAR(255)           DEFAULT NULL COMMENT 'Layout 或 views/xxx/index',
    redirect     VARCHAR(255)           DEFAULT NULL COMMENT '目录默认重定向',
    query_param  VARCHAR(500)           DEFAULT NULL COMMENT '路由 query（JSON）',
    perm_code    VARCHAR(100)           DEFAULT NULL COMMENT '关联权限编码',
    menu_type    VARCHAR(20)   NOT NULL DEFAULT 'MENU' COMMENT 'DIR / MENU / BUTTON',
    icon         VARCHAR(100)           DEFAULT NULL COMMENT '图标',
    sort_order   INT           NOT NULL DEFAULT 0,
    visible      TINYINT(1)    NOT NULL DEFAULT 1 COMMENT '侧边栏显示',
    hidden       TINYINT(1)    NOT NULL DEFAULT 0 COMMENT '隐藏路由',
    keep_alive   TINYINT(1)    NOT NULL DEFAULT 0 COMMENT '页面缓存',
    always_show  TINYINT(1)    NOT NULL DEFAULT 0 COMMENT '始终显示父目录',
    is_frame     TINYINT(1)    NOT NULL DEFAULT 0 COMMENT '是否外链',
    frame_url    VARCHAR(500)           DEFAULT NULL COMMENT '外链地址',
    enabled      TINYINT(1)    NOT NULL DEFAULT 1,
    remark       VARCHAR(255)           DEFAULT NULL,
    created_at   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_menu_code (menu_code),
    KEY idx_parent_id (parent_id),
    KEY idx_ancestors (ancestors(191)),
    KEY idx_level (level),
    KEY idx_perm_code (perm_code),
    KEY idx_menu_type (menu_type),
    KEY idx_sort_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统菜单表';

-- 平台统一前端菜单初始化数据
-- 来源：apps/platform-web/src/layout/nav.ts 中 platformNavItems
INSERT INTO sys_menu (
    id, parent_id, ancestors, level, menu_name, menu_code,
    route_path, route_name, component, redirect, query_param, perm_code,
    menu_type, icon, sort_order, visible, hidden, keep_alive,
    always_show, is_frame, frame_url, enabled, remark
) VALUES
    (10000, 0, '0', 1, '平台首页', 'platform:dashboard', '/dashboard', 'Dashboard', 'views/platform/DashboardPage', NULL, NULL, NULL, 'MENU', 'DataAnalysis', 10, 1, 0, 0, 0, 0, NULL, 1, '统一平台首页'),

    (10100, 0, '0', 1, '知识管理', 'platform:km', '/km', 'KnowledgeManagement', 'Layout', '/km/bases', NULL, NULL, 'DIR', 'Collection', 20, 1, 0, 0, 1, 0, NULL, 1, '知识管理一级菜单'),
    (10101, 10100, '0,10100', 2, '知识库管理', 'platform:km:bases', '/km/bases', 'KnowledgeBases', 'views/km/KnowledgeList', NULL, NULL, NULL, 'MENU', NULL, 10, 1, 0, 0, 0, 0, NULL, 1, NULL),
    (10102, 10100, '0,10100', 2, '文档与素材', 'platform:km:resources', '/km/resources', 'KnowledgeResources', 'views/platform/km/DocumentsPage', NULL, NULL, NULL, 'MENU', NULL, 20, 1, 0, 0, 0, 0, NULL, 1, NULL),
    (10103, 10100, '0,10100', 2, '知识检索', 'platform:km:search', '/km/search', 'KnowledgeSearch', 'views/km/SearchPage', NULL, NULL, NULL, 'MENU', NULL, 30, 1, 0, 0, 0, 0, NULL, 1, NULL),

    (10200, 0, '0', 1, '智能问答', 'platform:qa', '/qa', 'QaManagement', 'Layout', '/qa/chat', NULL, NULL, 'DIR', 'ChatDotRound', 30, 1, 0, 0, 1, 0, NULL, 1, '智能问答一级菜单'),
    (10201, 10200, '0,10200', 2, '智能对话', 'platform:qa:chat', '/qa/chat', 'QaChat', 'views/qa/ChatView', NULL, NULL, NULL, 'MENU', NULL, 10, 1, 0, 0, 0, 0, NULL, 1, NULL),
    (10202, 10200, '0,10200', 2, '会话记录', 'platform:qa:conversations', '/qa/conversations', 'QaConversations', 'views/qa/Conversations', NULL, NULL, NULL, 'MENU', NULL, 20, 1, 0, 0, 0, 0, NULL, 1, NULL),
    (10203, 10200, '0,10200', 2, '检索测试', 'platform:qa:retrieval-test', '/qa/retrieval-test', 'QaRetrievalTest', 'views/qa/admin/RetrievalTest', NULL, NULL, 'qa:retrieval-test:view', 'MENU', NULL, 30, 1, 0, 0, 0, 0, NULL, 1, '管理员可见'),
    (10204, 10200, '0,10200', 2, '问答配置', 'platform:qa:settings', '/qa/settings', 'QaSettings', 'views/qa/admin/QaConfig', NULL, NULL, 'qa:settings:view', 'MENU', NULL, 40, 1, 0, 0, 0, 0, NULL, 1, '管理员可见'),

    (10300, 0, '0', 1, '报告生成', 'platform:reports', '/reports', 'ReportManagement', 'Layout', '/reports', NULL, NULL, 'DIR', 'DocumentCopy', 40, 1, 0, 0, 1, 0, NULL, 1, '报告生成一级菜单'),
    (10301, 10300, '0,10300', 2, '报告记录', 'platform:reports:list', '/reports', 'ReportList', 'views/reports/ReportListPage', NULL, NULL, NULL, 'MENU', NULL, 10, 1, 0, 0, 0, 0, NULL, 1, NULL),
    (10302, 10300, '0,10300', 2, '新建报告', 'platform:reports:new', '/reports/new', 'ReportCreate', 'views/reports/NewReportPage', NULL, NULL, NULL, 'MENU', NULL, 20, 1, 0, 0, 0, 0, NULL, 1, NULL),
    (10303, 10300, '0,10300', 2, '趋势统计', 'platform:reports:dashboard', '/reports/dashboard', 'ReportDashboard', 'views/reports/admin/AdminDashboardPage', NULL, NULL, 'reports:dashboard:view', 'MENU', NULL, 30, 1, 0, 0, 0, 0, NULL, 1, '管理员可见'),
    (10304, 10300, '0,10300', 2, '模板管理', 'platform:reports:templates', '/reports/templates', 'ReportTemplates', 'views/reports/admin/TemplateAdminPage', NULL, NULL, 'reports:templates:view', 'MENU', NULL, 40, 1, 0, 0, 0, 0, NULL, 1, '管理员可见'),
    (10305, 10300, '0,10300', 2, '素材映射', 'platform:reports:materials', '/reports/materials', 'ReportMaterials', 'views/platform/PlaceholderPage', NULL, NULL, 'reports:materials:view', 'MENU', NULL, 50, 1, 0, 0, 0, 0, NULL, 1, '管理员可见'),

    (10400, 0, '0', 1, '模型配置', 'platform:model-config', '/model-config', 'ModelConfigManagement', 'Layout', '/km/settings', NULL, 'model:config:view', 'DIR', 'SetUp', 50, 1, 0, 0, 1, 0, NULL, 1, '管理员可见'),
    (10401, 10400, '0,10400', 2, '知识模型配置', 'platform:model-config:km', '/km/settings', 'KnowledgeSettings', 'views/km/admin/EmbedConfig', NULL, NULL, 'km:settings:view', 'MENU', NULL, 10, 1, 0, 0, 0, 0, NULL, 1, '管理员可见'),
    (10402, 10400, '0,10400', 2, 'LLM / 报告模型配置', 'platform:model-config:llm', '/qa/llm', 'QaLlmSettings', 'views/qa/admin/LlmConfig', NULL, NULL, 'qa:llm:view', 'MENU', NULL, 20, 1, 0, 0, 0, 0, NULL, 1, '管理员可见，报告生成复用同一套 LLM 配置'),

    (10500, 0, '0', 1, '系统管理', 'platform:admin', '/admin', 'SystemManagement', 'Layout', '/admin/overview', NULL, 'system:manage', 'DIR', 'Management', 60, 1, 0, 0, 1, 0, NULL, 1, '管理员可见'),
    (10501, 10500, '0,10500', 2, '总览统计', 'platform:admin:overview', '/admin/overview', 'AdminOverview', 'views/platform/admin/SystemOverviewPage', NULL, NULL, 'system:overview:view', 'MENU', NULL, 10, 1, 0, 0, 0, 0, NULL, 1, '管理员可见'),
    (10502, 10500, '0,10500', 2, '用户管理', 'platform:admin:users', '/admin/users', 'AdminUsers', 'views/platform/admin/UserManagementPage', NULL, NULL, 'system:user:view', 'MENU', NULL, 20, 1, 0, 0, 0, 0, NULL, 1, '管理员可见'),
    (10503, 10500, '0,10500', 2, '角色权限', 'platform:admin:roles', '/admin/roles', 'AdminRoles', 'views/platform/admin/RolePermissionPage', NULL, NULL, 'system:role:view', 'MENU', NULL, 30, 1, 0, 0, 0, 0, NULL, 1, '管理员可见')
ON DUPLICATE KEY UPDATE
    parent_id = VALUES(parent_id),
    ancestors = VALUES(ancestors),
    level = VALUES(level),
    menu_name = VALUES(menu_name),
    route_path = VALUES(route_path),
    route_name = VALUES(route_name),
    component = VALUES(component),
    redirect = VALUES(redirect),
    query_param = VALUES(query_param),
    perm_code = VALUES(perm_code),
    menu_type = VALUES(menu_type),
    icon = VALUES(icon),
    sort_order = VALUES(sort_order),
    visible = VALUES(visible),
    hidden = VALUES(hidden),
    keep_alive = VALUES(keep_alive),
    always_show = VALUES(always_show),
    is_frame = VALUES(is_frame),
    frame_url = VALUES(frame_url),
    enabled = VALUES(enabled),
    remark = VALUES(remark);
